name: stripe_intent_data
description: A package to handle stripe payment's api responses and provides stripe intent details, charge details and customer details, it also create stipe cutomer ID if not available and returns equire data to process a payment and also returns a charge details
version: 0.1.6
homepage: https://github.com/samrat19/stripe_intent_data

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
